### ISSUE TITLE
Can not be renamed

### ISSUE THREAD

**Issue by Tarmizi-H** [arajnoha/zeronote#1]
Can't change the file name, i mean the title

**Comment by arajnoha** [comment]
Yes, technically, editing the Name input saves the note as a new one, so you would have to delete the original one. I've thought about this when deciding if it's worth adding it in, but it couldn't fit into 1kB limit. 
However, for any serious note taking, feel free to check my https://github.com/arajnoha/subnotes which has all the regular features like folders, moving them etc.
This was really a barebone version.
